name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Automatically Find index.html and Create Config
        run: |
          # This command searches for index.html and finds its folder name
          TARGET_DIR=$(dirname $(find . -name "index.html" | head -n 1) | sed 's|^\./||' | sed 's|^\.$||')
          
          # If it's in the root folder, use ".", otherwise use the folder path found
          if [ -z "$TARGET_DIR" ]; then TARGET_DIR="."; fi
          echo "Found index.html in directory: $TARGET_DIR"
          
          # Build the firebase.json dynamically
          echo "{\"hosting\": {\"public\": \"$TARGET_DIR\", \"ignore\": [\"firebase.json\", \"**/.*\", \"**/node_modules/**\"]}}" > firebase.json

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project fifawatch-2026
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
