name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - master # Change this to main if your default branch is called main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project fifawatch-2026
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
